### PR TITLE
chore: Upgrade to Laravel 10

### PR DESCRIPTION
**Pull request by eliseoeric**
This commit updates our composer file to support Laravel 10

### CODE REVIEW

**Comment by tryvin** [comment]
@eliseoeric don't we use master for our project? or do we specify a commit hash?

**Comment by eliseoeric** [comment]
@tryvin we use `master` - I just wanted to have the PR approved before merging directly

**Comment by tryvin** [comment]
@eliseoeric Won't this break our current build? As it removes the old laravel versions from it?

**Comment by eliseoeric** [comment]
@tryvin yep - my bad. 

What do you think about this approach:

1. [x] Tag the `master` branch in `laravel-sitemap` as `v9.0.1`
2. [x] Update the `jobs` composer file to use `^9.0.1` instead of `dev-master` as the version
3. [x] Merge this PR into `master`
4. [ ] Release a tag on `laravel-sitemap` after this PR has been merged for `v10.0.1`

**Comment by tryvin** [comment]
@eliseoeric agree with your approach, how do you want to implement it? You do and I just review?

**Comment by eliseoeric** [comment]
@tryvin I can knock it out. I'll send over a PR for `jobs` shortly.

**Review by tryvin — APPROVED** [review]

**Pull request merged**
